services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: horizon
      POSTGRES_USER: horizon
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Performance optimizations for full history sync on 64GB RAM server
    command: >
      postgres 
      -c shared_buffers=16GB
      -c effective_cache_size=48GB
      -c maintenance_work_mem=4GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=128MB
      -c default_statistics_target=100
      -c random_page_cost=1.0
      -c effective_io_concurrency=200
      -c work_mem=512MB
      -c max_worker_processes=16
      -c max_parallel_workers_per_gather=8
      -c max_parallel_workers=16
      -c max_parallel_maintenance_workers=8
      -c max_connections=200
      -c checkpoint_timeout=15min
      -c max_wal_size=8GB
      -c min_wal_size=2GB
      -c log_min_duration_statement=1000
      -c log_checkpoints=on
      -c autovacuum_naptime=15s
      -c autovacuum_max_workers=6
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "horizon"]
      interval: 10s
      retries: 5

  horizon:
    image: stellar/stellar-horizon:22.0.3 # pick an exact tag
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000" # Public API
      - "6060:6060" # Optional admin (metrics / pprof)
    environment:
      # --- core connection ---
      NETWORK: "${STELLAR_NETWORK:-pubnet}" # pubnet, testnet, or futurenet
      CAPTIVE_CORE_CONFIG_PATH: "/etc/captive-core/captive-core.cfg"
      CAPTIVE_CORE_STORAGE_PATH: "/var/horizon/core" # persists ledger buckets
      # --- ingestion ---
      INGEST: "${INGEST:-true}"
      HISTORY_RETENTION_COUNT: "${HISTORY_RETENTION_COUNT:-518400}" # ≈30 days default
      # --- database ---
      DATABASE_URL: "postgresql://horizon:${DB_PASSWORD}@db:5432/horizon?sslmode=disable"
      # --- ops & telemetry ---
      ADMIN_PORT: "${ADMIN_PORT:-6060}" # exposes /metrics
      LOG_LEVEL: "${LOG_LEVEL:-info}"
    volumes:
      - ./networks/${STELLAR_NETWORK:-pubnet}:/etc/captive-core # network-specific config
      - horizon_state:/var/horizon
    command: ["serve"]

volumes:
  postgres_data:
  horizon_state:
